title: PHP-Colors
description: This is an object-oriented color library for PHP 
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

github:
  zip_url: https://github.com/blasher/php-colors/zipball/master
  tar_url: https://github.com/blasher/php-colors/tarball/master

gems:
  - jekyll-mentions
